name-template: "$RESOLVED_VERSION 🤖"
tag-template: "v$RESOLVED_VERSION"
commitish: main
template: |
  ## What’s Changed

  $CHANGES

categories:
  - title: "🚨 Breaking Changes"
    label: "breaking"
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "🏡 Chore"
    label: "chore"
  - title: "🤓 Dependency Updates"
    label: "dependency"

autolabeler:
  - label: breaking
    branch: /breaking\/.+/
  - label: feature
    branch: /feature\/.+/
  - label: bug
    branch: /bug(s)?\/.+/
  - label: chore
    branch: /chore\/.+/
  - label: dependency
    branch: /renovate\/.+/

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "bug"
      - "chore"
      - "dependency"
