name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nodejs:
    uses: ./.github/workflows/nodejs.yml
    secrets: inherit
  action:
    uses: ./.github/workflows/action.yml
